
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';

const SUPABASE_URL = "https://sfcqvyquseghzwybddpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmY3F2eXF1c2VnaHp3eWJkZHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTUxOTEsImV4cCI6MjA1OTk3MTE5MX0.MnwgWh9UwEmt7Vwifkotv-ZNQQbC5lOdGFY4mOuXIyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
